# Generated by Django 3.2.5 on 2022-07-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
