# Generated by Django 3.2.5 on 2022-07-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keysite', '0002_alter_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=200)),
                ('cmd_category', models.CharField(choices=[('Feaquently_Used_Key', 'Feaquently_Used_Key'), ('Ribbon', 'Ribbon'), ('Navigate', 'Navigate'), ('Preview', 'Preview'), ('Select', 'Select'), ('Extend_Selection', 'Extend_Selection'), ('Edit', 'Edit'), ('Align', 'Align'), ('Format', 'Format'), ('Insert', 'Insert'), ('Web', 'Web'), ('Table', 'Table'), ('Review', 'Review'), ('Reference', 'Reference'), ('Mail', 'Mail'), ('Field', 'Field'), ('Language', 'Language'), ('View', 'View'), ('Outline', 'Outline'), ('Fn_key', 'Fn_key')], max_length=200)),
                ('cmd_name', models.CharField(max_length=200)),
                ('cmd_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
