# Generated by Django 3.2.5 on 2022-07-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keysite', '0003_auto_20220707_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmd',
            name='choice_OS',
            field=models.CharField(choices=[('MacOS', 'MacOS'), ('Windows', 'Windows')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cmd',
            name='program',
            field=models.CharField(choices=[('HWP', 'HWP'), ('Word', 'Word')], max_length=200),
        ),
    ]
