# Generated by Django 3.2.5 on 2022-07-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keysite', '0004_auto_20220708_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmd',
            old_name='cmd_description',
            new_name='cmd_discription',
        ),
    ]
