# Generated by Django 3.2.5 on 2022-07-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keysite', '0006_rename_cmd_discription_cmd_cmd_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmd',
            name='cmd_category',
        ),
    ]
